_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.7
            "8":
                - 2
                - 5
            "12": 0.19.7
            "13": linux-x86_64
